### ISSUE TITLE
tg的sendPhoto老出错你有没有啥办法

### ISSUE THREAD

**Issue by dlnn** [soxft/xneteasebot#1]
想弄个本子机器人 tg的sendPhoto老出错你有没有啥办法

**Comment by soxft** [comment]
嗯？能不能具体描述一下哪里出错

**Comment by dlnn** [comment]
- -就那个url photo wrong file identifier/http url specified 大概就是TG服务器看脸拉取url图片

**Comment by soxft** [comment]
telegram发送图片的图片格式是有一定要求的我记得

**Comment by dlnn** [comment]
- -就是看脸拉取 去tg的缓存机器人里手动刷新了十来次之后能缓存了才能发

**Comment by soxft** [comment]
不是吧，我是直接用的链接，发一次之后就可以直接用file_id了

**Comment by dlnn** [comment]
我也是直接发链接但是同一个图床有的tg服务器无法缓存得去机器人里手动刷新到缓存成功为止才能发



------------------ 原始邮件 ------------------
发件人: xcsoft <notifications@github.com&gt;
发送时间: 2020年8月3日 20:39
收件人: soxft/xneteasebot <xneteasebot@noreply.github.com&gt;
抄送: dlnn <admin@dlnn.net&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[soxft/xneteasebot] tg的sendPhoto老出错你有没有啥办法 (#1)





 
不是吧，我是直接用的链接，发一次之后就可以直接用file_id了

**Comment by soxft** [comment]
可能图床速度比较慢？tg的api貌似有超时限制的

**Comment by dlnn** [comment]
这就不清楚我感觉挺快的有的图甚至40k都拉不了
